/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "cal.h"

#define MAX_LEN 256

void
rpc_prog_1(char *host, char *input)
{
	CLIENT *clnt;
	int  *result_1;
	char * calculate_1_arg;
    char buf[MAX_LEN];
#ifndef	DEBUG
	clnt = clnt_create (host, RPC_PROG, RPC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
    sprintf(buf,"%s",input);
    calculate_1_arg=buf;
	result_1 = calculate_1(&calculate_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
    else{
        printf("Answer: %d\n", *result_1);
    }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
    char input[MAX_LEN];
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
  
    printf("Input : ");
    scanf("%s", input);
	rpc_prog_1 (host, input);
exit (0);
}
